Subida 1

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -9,34 +9,47 @@ on:
                     - SI
                     - NO
                 default: SI
+
 jobs:
     build:
         runs-on: ubuntu-latest
         outputs:
-            build_status: ${{ steps.build.outputs.resultado == 'SI' && 'success' || 'fail' }}
+            build_status: ${{ steps.set_status.outputs.build_status }}
         steps:      
-            - name: 'Print GITHUB_OUTPUT path'       
+            - name: Print GITHUB_OUTPUT path
               run: |
                 echo "var -->> $GITHUB_OUTPUT"
+            
             - name: Build
               id: build
               run: |
                 echo "Building"
-                echo "variable=${{inputs.result}}" >> "$GITHUB_OUTPUT"
+                echo "resultado=${{ inputs.result }}" >> $GITHUB_ENV
+            
+            - name: Set build status
+              id: set_status
+              run: |
+                if [[ "${{ inputs.result }}" == "SI" ]]; then
+                  echo "build_status=success" >> $GITHUB_OUTPUT
+                else
+                  echo "build_status=fail" >> $GITHUB_OUTPUT
+                fi
 
     deploy:
         runs-on: ubuntu-latest
+        needs: build
         if: ${{ needs.build.outputs.build_status == 'success' }}    
         steps:      
             - name: Deploy                                     
               run: |
                 echo "Deploying"
+
     rollback:
-      runs-on: ubuntu-latest
-      needs: build
-      if: ${{ needs.build.outputs.build_status != 'success' }}    
-      steps:      
-          - name: Rollback                                     
-            run: |
-              echo "Rollback"
-              exit 1
+        runs-on: ubuntu-latest
+        needs: build
+        if: ${{ needs.build.outputs.build_status != 'success' }}    
+        steps:      
+            - name: Rollback                                     
+              run: |
+                echo "Rollback"
+                exit 1
